# Generated by Django 4.2.29 on 2026-04-27 02:46

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('GENERATE', 'Generate')], max_length=10)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=15)),
                ('station_name', models.CharField(default='All Stations', max_length=100)),
                ('station_index', models.CharField(default='-', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_index', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_index', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to=backend.models.upload_file_path)),
                ('date', models.CharField(max_length=20)),
                ('file_type', models.CharField(choices=[('PDF', '6H Daily Report'), ('IMG', 'Rainfall Image')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('station_index', 'date', 'file_type')},
            },
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('date', models.DateField()),
                ('file_type', models.CharField(max_length=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.station')),
            ],
        ),
    ]
