# Generated by Django 4.2.29 on 2026-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_index', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='rescue/')),
                ('date', models.CharField(max_length=20)),
                ('rescue_type', models.CharField(choices=[('24HRR', '24HRR'), ('MAXRR', 'MaxRR'), ('SUMMAXRR', 'SumMaxRR')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
